# this file is just an example of how to set up a local server for this project, you can change the ServerName and DocumentRoot to match your local setup

<VirtualHost *:80>
    ServerName education-one.local # example for a local server
    DocumentRoot "directory/to/the/root/folder/of/this/project" # project public folder on your machine
    <Directory "directory/to/the/public/folder/of/this/project"> # project public folder on your machine
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
